services:
  - type: web
    name: zaiko-app
    env: docker
    plan: free
    region: singapore
    branch: main
    buildFilter:
      paths:
        - Dockerfile
        - start.sh
    repo: https://github.com/jancord/push

