services:
  - type: web
    name: zaiko-app
    env: php
    region: singapore
    plan: free
    buildCommand: |
      composer install --no-dev
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: zaiko-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: zaiko-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: zaiko-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: zaiko-db
          property: password

databases:
  - name: zaiko-db
    region: singapore
    plan: free

